echo ""
echo "                       ___ ___     "
echo "             ____     /  / \  \  "
echo "            / ___\   /  /   \  \  "
echo "           / /_/  > (  (     )  ) "
echo "           \___  /   \  \   /  /  "
echo "          /_____/     \__\ /__/  "
echo "                                   "
echo ""
