module Gfxt.Help (help) where

help :: String
help = unlines
  [ ""
  , "# XMonad keybindings #"
  , ""
  , "Key bindings (meta key is commnad or win):"
  , "Meta + Enter           switch focused window to master window"
  , "Meta + Shift + C       close focused window"
  , "Meta + Shift + Q       close xmonad"
  , "Meta + Shift + N       switch next workspace"
  , "Meta + Shift+ P        switch previous workspace"
  , "Meta + Shift+ L        Lock screen (Slimlock)"
  , "Meta + Shift+ Enter    start a terminal (Rxvt-unicode)"
  , "Meta + H               make a focus window smaller"
  , "Meta + L               make a focus window bigger"
  , "Meta + P               lanuch dmenu"
  , "Meta + G               lanuch GridSelect"
  , "Meta + B               start a web browser (Firefox Nightly)"
  , "Meta + S               start a client software of online strage (Wuala)"
  , "Meta + A               start a editor (GVim)"
  , "Meta + W               switch next screen"
  , "meta + E               switch previous screen"
  , "Meta + F1              paste a private email address (1)"
  , "Meta + F2              paste a private email address (2)"
  , "Meta + F3              paste a public email address"
  , "Meta + \\             open help window"
  , ""
  , "Startup programs and workspaces:"
  , "/---------------------------------------------------\\ "
  , "| Num   | ID        | Program                            |"
  , "|-------+-----------+------------------------------------|"
  , "| 1     | > term    | *Rxvt-unicode (with shell or vim)  |"
  , "| 2     | > browser | *Firefox Nightly, Chromium         |"
  , "| 3     | > mailer  | *Thunderbird                       |"
  , "| 4     | > psmgr   | KeePassX                           |"
  , "| 5     | > idea    | IntelliJ Idea                      |"
  , "| 6     | > paint   | GIMP, Inkscape                     |"
  , "| 7     | > player  | VLC                                |"
  , "| 8     | > strage  | Wuala                              |"
  , "| 9     | > skype   | Skype                              |"
  , "| 10    | > office  | LibreOffice                        |"
  , "| 11~18 | > B~I     | (None)                             |"
  , "\\-------------------------------------------------------/"
  , "*) These programs start after staring up xmonad" ]
